version: '3.8'

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/home/schedule-manager
  stdin_open: true
  tty: true

services:
  api:
    <<: *app
    command: >
      bash -c "cd api && npm i -g nodemon && yarn && yarn dev"
    ports:
      - 3500:3500
      - 3000:3000
    environment:
      API_PORT: 3500
      API_HOST: localhost:3500